### ISSUE TITLE
Can you upload code source for version 0.9.0305 ?

### ISSUE THREAD

**Issue by SuperMax3d** [froque/Make-My-Manifest#1]
Hi,

I have an utility that works on 0.9.0305, but doesn't work on 0.12.0308. It says "The application has failed to start because its side-by-side configuration incorrect.". By the way, thanks for your app!

**Comment by SuperMax3d** [comment]
Finally I found out my problem, by looking at your comments, I found out it was fixed by re-enabling "If StrPtr(.ThreadingModel) <> 0 Then" in frmMake.frm

'''This is no longer conditional as of version 0.12, since there may well be
'''legitimate non-creatable classes in an OCX that won't have a ThreadingModel.
'''                            'Registered class?  Then write component file class.
                            If StrPtr(.ThreadingModel) <> 0 Then

Thanks!

**Comment by froque** [comment]
@SuperMax3d just to be clear I didn't wrote this. I just uploaded to github because it was very hard to found the source code.
